#ifndef WDGRV_REGS_H
#define WDGRV_REGS_H
#include "stdint.h"
#define WDGRV_REGS_WDCSR_WDEN_BIT_WIDTH 1
#define WDGRV_REGS_WDCSR_WDEN_BIT_MASK 0x1
#define WDGRV_REGS_WDCSR_WDEN_BIT_OFFSET 0
#define WDGRV_REGS_WDCSR_RVD1_BIT_WIDTH 1
#define WDGRV_REGS_WDCSR_RVD1_BIT_MASK 0x1
#define WDGRV_REGS_WDCSR_RVD1_BIT_OFFSET 1
#define WDGRV_REGS_WDCSR_S1WTO_BIT_WIDTH 1
#define WDGRV_REGS_WDCSR_S1WTO_BIT_MASK 0x1
#define WDGRV_REGS_WDCSR_S1WTO_BIT_OFFSET 2
#define WDGRV_REGS_WDCSR_S2WTO_BIT_WIDTH 1
#define WDGRV_REGS_WDCSR_S2WTO_BIT_MASK 0x1
#define WDGRV_REGS_WDCSR_S2WTO_BIT_OFFSET 3
#define WDGRV_REGS_WDCSR_WTOCNT_BIT_WIDTH 10
#define WDGRV_REGS_WDCSR_WTOCNT_BIT_MASK 0x3ff
#define WDGRV_REGS_WDCSR_WTOCNT_BIT_OFFSET 4
#define WDGRV_REGS_WDCSR_RVD2_BIT_WIDTH 18
#define WDGRV_REGS_WDCSR_RVD2_BIT_MASK 0x3ffff
#define WDGRV_REGS_WDCSR_RVD2_BIT_OFFSET 14
#define WDGRV_REGS_WDCSR_BYTE_WIDTH 4
#define WDGRV_REGS_WDCSR_BYTE_SIZE 4
#define WDGRV_REGS_WDCSR_BYTE_OFFSET 0x0
#define WDGRV_REGS_WDCNT_CNT_BIT_WIDTH 32
#define WDGRV_REGS_WDCNT_CNT_BIT_MASK 0xffffffff
#define WDGRV_REGS_WDCNT_CNT_BIT_OFFSET 0
#define WDGRV_REGS_WDCNT_BYTE_WIDTH 4
#define WDGRV_REGS_WDCNT_BYTE_SIZE 4
#define WDGRV_REGS_WDCNT_BYTE_OFFSET 0x4
typedef struct {
  uint32_t wdcsr;
  uint32_t wdcnt;
} wdgrv_regs_t;
#endif
